### ISSUE TITLE
error 

### ISSUE THREAD

**Issue by ctqvvx** [Kyou-Izumi/advanced-discord-owo-tool-farm#46]
error when npm start is typed in termux 
![image](https://github.com/user-attachments/assets/bbcddcdd-2c33-4ced-866d-feb587941617)

**Comment by Kyou-Izumi** [comment]
> error when npm start is typed in termux ![image](https://private-user-images.githubusercontent.com/186373589/387566176-bbcddcdd-2c33-4ced-866d-feb587941617.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIwMDY0NzcsIm5iZiI6MTczMjAwNjE3NywicGF0aCI6Ii8xODYzNzM1ODkvMzg3NTY2MTc2LWJiY2RkY2RkLTJjMzMtNGNlZC04NjZkLWZlYjU4Nzk0MTYxNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExOVQwODQ5MzdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yNWZlMzJmYzUxNThkZjQyMzc4NjJjMjg4YWVhZTdlMDM5ZmJjOTc5YzBjN2Q0Yjg1NjA1OGEzYTk0NmJiMjQwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.RnwckshHDgHKpRTqZukCMxI2Z1ah8tFKVai2JsjyG4Q)

Fixed! Please pull the repo again
